pipeline {
    agent any

     tools {
        nodejs 'NodeJS Plugin'  // Ensure this matches the name you set in Global Tool Configuration
    }

    stages{
        stage('Clone'){
            steps {
                git branch : 'main', url:'https://github.com/ShubhamPrasad-2711/portfolio.git'
            }
        }

        stage('See ALl file'){
            steps {
            script {
             dir('portfolio/portfolio-website') {
                sh 'ls -R'  // List all files and directories recursively
             }
        }
    }
        }
           

        stage('Install Dependencies') {
            steps{
                script {
                    dir('portfolio/portfolio-website') {
                        sh 'ls -al'
                        sh 'npm install'
                        sh 'npm install -g @angular/cli'
                    }
                }
            }
        }

        stage('Build Project') {
            steps {
                script {
                   dir('portfolio/portfolio-website'){
                     sh 'ng build'
                   }
                }
            }
        }

        stage('Deployment') {
            steps{
                echo 'Deployment Phase Here!!!'
            }
        }
    }
}